
name: CI/CD Pipeline

# Define the events that trigger the workflow
on:
  push:
    branches:
      - main
  workflow_dispatch:

# Define the build job
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v2

      # Build the Docker image
      - name: Build Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          tags: jayvirrathi/nodejs:v1

      # Set the image tag as an output
      - name: Set image tag output
        id: tag
        run: echo "::set-output name=tag::jayvirrathi/nodejs:v1"

  # Define the deploy job
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v2

      # Replace the image tag in the deployment file
      - name: Replace image tag in deployment file
        run: yq e '.spec.template.spec.containers[0].image = "jayvirrathi/nodejs:v1"' -i deployment/deployment.yaml

        #run: kubectl apply -f deployment/deployment.yaml
        #run : kubectl get nodes

